<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildThisFileDirectory)../../build/Common.props" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net6.0;netstandard2.0</TargetFrameworks>
    <Description>MongoDbClient instrumentation for OpenTelemetry .NET</Description>
    <PackageTags>$(PackageTags);MongoDbClient</PackageTags>
    <Title>OpenTelemetry.Instrumentation.MongoDbClient</Title>
    <Copyright>Copyright The OpenTelemetry Authors</Copyright>
    <PackageProjectUrl>https://opentelemetry.io/</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <MinVerTagPrefix>Instrumentation.MongoDbClient-</MinVerTagPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver.Core" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Diagnostics.DiagnosticSource" />
  </ItemGroup>
</Project>
