<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Authors>DevComputaria</Authors>
    <Company>DevComputaria</Company>
    <Copyright>Copyright 2026 DevComputaria</Copyright>
    <PackageOutputPath>$(MSBuildThisFileDirectory)../artifacts/package/release</PackageOutputPath>
    <PackageTags>OpenTelemetry;Instrumentation;MongoDB</PackageTags>
    <MinVerTagPrefix>Instrumentation.MongoDbClient-</MinVerTagPrefix>
  </PropertyGroup>
</Project>
