<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageTags>OpenTelemetry;Instrumentation;MongoDB</PackageTags>
    <MinVerTagPrefix>Instrumentation.MongoDbClient-</MinVerTagPrefix>
  </PropertyGroup>
</Project>
