# Called by ci.yml to build & test project files
name: Build Component

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      project-build-commands:
        default: ''
        required: false
        type: string
      code-cov-name:
        required: true
        type: string
      code-cov-prefix:
        default: 'unittests'
        required: false
        type: string
      os-list:
        default: '[ "windows-2025", "ubuntu-24.04" ]'
        required: false
        type: string
      tfm-list:
        default: '[ "net8.0" ]'
        required: false
        type: string
      trigger:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-test:
    name: build-test

    strategy:
      fail-fast: ${{ inputs.trigger == 'merge_group' }}
      matrix:
        os: ${{ fromJSON(inputs.os-list) }}
        version: ${{ fromJSON(inputs.tfm-list) }}

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    env:
      DISABLE_APP_DOMAIN: ${{ matrix.version == 'net462' && 'false' || 'true' }}
      PROJECT_NAME: ${{ inputs.project-name }}
      PROJECT_BUILD_COMMANDS: ${{ inputs.project-build-commands }}
      TARGET_FRAMEWORK: ${{ matrix.version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false
        show-progress: false

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0

    - name: dotnet restore ${{ inputs.project-name }}
      shell: pwsh
      run: dotnet restore ${env:PROJECT_NAME} ${env:PROJECT_BUILD_COMMANDS}

    - name: dotnet build ${{ inputs.project-name }}
      shell: pwsh
      run: dotnet build ${env:PROJECT_NAME} --configuration Release --no-restore ${env:PROJECT_BUILD_COMMANDS}

    - name: dotnet test ${{ inputs.project-name }}
      shell: pwsh
      run: >
        dotnet test ${env:PROJECT_NAME}
        --collect:"Code Coverage"
        --results-directory:TestResults
        --framework ${env:TARGET_FRAMEWORK}
        --configuration Release
        --no-restore
        --no-build
        -- RunConfiguration.DisableAppDomain=${env:DISABLE_APP_DOMAIN}

    - name: Install coverage tool
      shell: pwsh
      env:
        DOTNET_COVERAGE_VERSION: '18.7.0'
      run: dotnet tool install -g dotnet-coverage --version ${env:DOTNET_COVERAGE_VERSION}

    - name: Merging test results
      run: dotnet-coverage merge -f cobertura -o ./TestResults/Cobertura.xml ./TestResults/**/*.coverage

    - name: Upload code coverage ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      continue-on-error: true
      timeout-minutes: 5
      env:
        OS: ${{ matrix.os }}
        TFM: ${{ matrix.version }}
      with:
        disable_search: true
        disable_telem: true
        env_vars: OS,TFM
        files: TestResults/Cobertura.xml
        flags: ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
        name: Code Coverage for ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }} on [${{ matrix.os }}.${{ matrix.version }}]
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test results ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
      if: ${{ !cancelled() && hashFiles('./TestResults/junit.xml') != '' }}
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      continue-on-error: true
      timeout-minutes: 5
      with:
        disable_search: true
        disable_telem: true
        env_vars: OS,TFM
        files: TestResults/junit.xml
        flags: ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
        name: Test results for ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }} on [${{ matrix.os }}.${{ matrix.version }}]
        report_type: test_results
        token: ${{ secrets.CODECOV_TOKEN }}
