# Runs dotnet format to check code style compliance
name: dotnet-format

on:
  workflow_call:

permissions:
  contents: read

jobs:
  dotnet-format:
    name: dotnet-format
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false
        show-progress: false

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Check formatting
      run: dotnet format --verify-no-changes --verbosity diagnostic
